[package]
name = "memrustd"
version = "0.1.0"
authors = ["TJ White <thjwhite@gmail.com>"]

[dependencies]
mio="0.5"
slab="0.1.0"
bytes="0.3.0"
nix = { git = "https://github.com/carllerche/nix-rust", rev = "c4257f8a76" }
